
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import tkinter as tk
import os.path
import rosto_em_imagem
import texto_em_docs
import texto_em_xlsx
import fitz
import openpyxl
from docx import Document
from tkinter import *
from tkinter import PhotoImage as pht
from tkinter import messagebox

import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"Arquivos\teste\assetsGUI\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)



class MinhaGUI:
    def __init__(self):
        # Window setup from code 2
        self.window = Tk()
        self.window.geometry("1200x800")
        self.window.configure(bg="#000000")

        # Canvas creation from code 2
        self.canvas = Canvas(
            self.window,
            bg="#000000",
            height=800,
            width=1200,
            bd=0,
            highlightthickness=0,
            relief="ridge",
        )
        
        self.canvas.place(x = 0, y = 0)
        image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = self.canvas.create_image(
            600.0,
            181.0,
            image=image_image_1
        )

        # Label and buttons from code 1 (modify positions if needed)
        self.canvas.place(x = 0, y = 0)
        image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = self.canvas.create_image(
            600.0,
            181.0,
            image=image_image_1
        )

        self.canvas.create_text(
            357.0,
            386.0,
            anchor="nw",
            text="Indique o caminho que deve ser utilizado:",
            fill="#FFFFFF",
            font=("JostRoman Bold", 24 * -1)
        )

      

        self.entrada = Entry(self.canvas, width=40, bg="#D9D9D9", fg="#000716", font=50)
        self.entrada.place(x=357.0, y=446.0, width=470.0, height=35.0)  # Adjust position as needed

        # Button elements with images from code 2
        button_image_1 = PhotoImage(file=r"Arquivos\teste\assetsGUI\frame0\button_1.png") if relative_to_assets else PhotoImage(file=r"Arquivos\teste\assetsGUI\frame0\button_1.png")
        button_image_2 = PhotoImage(file=r"Arquivos\teste\assetsGUI\frame0\button_2.png") if relative_to_assets else PhotoImage(file=r"Arquivos\teste\assetsGUI\frame0\button_2.png")

        self.botao = Button(
            self.canvas,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=self.exibe,
            relief="flat",
        )
        self.botao.place(x=379.0, y=527.0, width=213.0, height=35.0)  # Adjust position as needed

        self.botao_sair = Button(
            self.canvas,
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=self.window.quit,
            relief="flat",
        )
        self.botao_sair.place(x=600.0, y=527.0, width=213.0, height=35.0)  # Adjust position as needed

        self.botao_grafico = Button(
            self.canvas,
            text="Abrir Gráfico",
            command=self.abrir_grafico,
            bg="#D9D9D9",
            fg="#000000",
            background="#26ffff", 
            font=("Jost", 14, "bold"),
            relief="flat",
        )
        self.botao_grafico.place(x=500, y=600, width=213, height=35)

        # Prevent window resizing from code 2
        self.window.resizable(False, False)

        # Main loop from code 1
        mainloop()

    def exibe(self):
        for path, directories, files in os.walk(self.entrada.get()): #Caminho de arquivos a ser analisado
          for file in files:
               if file.endswith(".PNG") or file.endswith(".jpg") or file.endswith(".jpeg") or file.endswith(".png"): #Definindo os tipos de arquivos de imagens
                    caminho = os.path.join(path, file)  # Apontando o caminho do arquivo para uma variável
                    #Chamar módulo
                    rosto_em_imagem.imagem(caminho, file, path)
               elif file.endswith(".pdf"): #Definindo os tipos de arquivos de texto
                    caminho = os.path.join(path, file)
                    doc = fitz.open(caminho)
                    text = ""
                    for page in doc:
                         text+=page.get_text()
                         texto_em_docs.texto(caminho, file, path, text)
               elif file.endswith(".docx") or file.endswith(".doc"):
                    caminho = os.path.join(path, file)
                    doc = Document(caminho)
                    text = '\n'.join([p.text for p in doc.paragraphs])
                    texto_em_docs.texto(caminho, file, path, text)

               elif file.endswith(".xlsx"):
                    caminho = os.path.join(path, file)
                    workbook = openpyxl.load_workbook(caminho)
                    texto = ""
                    for sheet in workbook:
                        for row in sheet.iter_rows():
                            for cell in row:
                                texto += str(cell.value) + "\n"
                    texto_em_xlsx.texto(caminho, file, path, texto)

        messagebox.showinfo("GetSens3", "Análise feita com sucesso!")

    def abrir_grafico(self):
        # Função para ação do botão "Abrir Gráfico"
        x = [1, 2, 3, 4]
        y = [2, 3, 4, 3]

        # criando a "figura" para comportar os gráficos e formar nosso Dashboard
        Figura = plt.figure(figsize=(12, 6))
        Figura.suptitle('Harry Potter menino maravilhoso')

        # adicionando a primeira figura
        Figura.add_subplot(331)

        plot1 = plt.plot(x, y, label='dados ')
        plot1 = plt.title('número de arquivos com dados relevantes')

        plt.legend()

        # adicionando o segundo plot na figura
        Figura.add_subplot(332)
        # segundo gráfico teste
        cores = ['green', 'red', 'blue']
        plot2 = plt.bar(x, y, label='número de sugadinhas', color=cores)
        plot2 = plt.title('número de cpfs encontrados')

        plt.legend()

        # adicionando o 3 gráfico
        Figura.add_subplot(333)
        # terceiro gráfico teste
        plot3 = plt.plot(x, y)
        plot3 = plt.title('tipo de dado mais encontrado')

        plt.legend()

        # SEGUNDA LINHA DA FIGURA

        # adicionando o 4 gráfico
        Figura.add_subplot(334)
        # terceiro gráfico teste
        fatiax = [3, 2, 4]
        cores = ['green', 'red', 'blue']
        plot4 = plt.pie(fatiax, colors=cores)
        plot4 = plt.title('tipo de dado mais encontrado')

        plt.legend()

        # adicionando uma terceira figura
        Figura.add_subplot(335)
        valorx = [5, 7, 3, 9]
        valory = [1, 2, 3, 4]
        plot4 = plt.scatter(valorx, valory, label='cpf, tamanho peniano')

        plt.show()

        plt.close()  # Fecha a janela do Matplotlib após desenhar o gráfico

        # Rodando
        mainloop()

gui = MinhaGUI()